/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ufes.gestaodecontatospss.view;

import javax.swing.JMenuItem;

/**
 *
 * @author Rafael e Heflain
 */
public class PrincipalView extends javax.swing.JFrame {
    
    public PrincipalView() {
      

        initComponents();
        this.setLocationRelativeTo(this.getParent());
        this.setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mbMenuPrincipal = new javax.swing.JMenuBar();
        bntOpcoes = new javax.swing.JMenu();
        btnNovoContato = new javax.swing.JMenuItem();
        btnListarContatos = new javax.swing.JMenuItem();
        btnFechar = new javax.swing.JMenuItem();
        btnJanela = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de pessoas");

        bntOpcoes.setText("Opções");

        btnNovoContato.setText("Novo Contato");
        btnNovoContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoContatoActionPerformed(evt);
            }
        });
        bntOpcoes.add(btnNovoContato);

        btnListarContatos.setText("Listar Contatos");
        btnListarContatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarContatosActionPerformed(evt);
            }
        });
        bntOpcoes.add(btnListarContatos);

        btnFechar.setText("Fechar o Sistema");
        bntOpcoes.add(btnFechar);

        mbMenuPrincipal.add(bntOpcoes);

        btnJanela.setText("Janela");
        mbMenuPrincipal.add(btnJanela);

        setJMenuBar(mbMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoContatoActionPerformed
        
    }//GEN-LAST:event_btnNovoContatoActionPerformed

    private void btnListarContatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarContatosActionPerformed
        
    }//GEN-LAST:event_btnListarContatosActionPerformed

    public JMenuItem getBtnFechar() {
        return btnFechar;
    }

    public JMenuItem getBtnListarContatos() {
        return btnListarContatos;
    }

    public JMenuItem getBtnNovoContato() {
        return btnNovoContato;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu bntOpcoes;
    private javax.swing.JMenuItem btnFechar;
    private javax.swing.JMenu btnJanela;
    private javax.swing.JMenuItem btnListarContatos;
    private javax.swing.JMenuItem btnNovoContato;
    private javax.swing.JMenuBar mbMenuPrincipal;
    // End of variables declaration//GEN-END:variables
    
}
